
config:
  backup: false
  create: true
  dotpath: .
  instignore:
    - '*/__pycache__/*'
actions:
  pre:
    enable_perm_sudo: echo "ZWNobyBEdXJpbmcgdGhlIGluc3RhbGwsIHlvdXIgdXNlciB3aWxsIGJlIGFibGUgdG8gcnVuIHN1ZG8gd2l0aG91dCBwYXNzd29yZCwgdG8gaGF2ZSBhIHNpbGVudCBpbnN0YWxsIHdpdGhvdXQgeW91ciBhY3Rpb24hO3NsZWVwIDEwO2VjaG8gIiRVU0VSIEFMTD0oQUxMKSBOT1BBU1NXRDogQUxMIiB8IHN1ZG8gdGVlIC9ldGMvc3Vkb2Vycy5kLzAxX2BlY2hvICRVU0VSYF9ub3Bhc3N3ZAo=" | base64 -d | bash
  post:
    01_install_packages: yay -Syyuu --noconfirm --needed - < {{@@ _dotfile_abs_dst @@}}
    02_change_shell: sudo chsh -s /bin/zsh $USER
    chmod_dst_folder: chmod {0} {{@@ _dotfile_abs_dst @@}}/*
    03_add_user_to_groups: sudo usermod -aG games,network,power,polkitd,vboxusers,usbmux,wireshark,docker,rfkill,users,video,storage,optical,kvm,input,disk,audio,wheel $USER
    04_fix_desktop_portals: echo "cGFja2FnZXM9JCh5YXkgLVEgfCBncmVwIC1QICd4ZGctZGVza3RvcC1wb3J0YWwoPyEoIHwtaHlwcmxhbmQtZ2l0KSknIHwgY3V0IC1kICcgJyAtZiAxKTsgaWYgW1sgLW4gIiRwYWNrYWdlcyIgXV07IHRoZW4gZWNobyAkcGFja2FnZXMgfCB4YXJncyB5YXkgLVIgLS1ub2NvbmZpcm07IGVsc2UgZWNobyAiTm8gcGFja2FnZXMgZm91bmQuIjsgZmkK" | base64 -d | bash
    05_disable_perm_sudo: echo "ZWNobyBJbnN0YWxsYXRpb24gZmluaXNoZWQsIGRlbGV0aW5nIHN1ZG8td2l0aG91dC1wYXNzIGZpbGU7c2xlZXAgNTtzdWRvIHJtIC1mIC9ldGMvc3Vkb2Vycy5kLzAxX3J5YW5fbm9wYXNzd2QK" | base64 -d | bash
dotfiles:
  pacman:
    src: pacman/pacman.conf
    dst: /etc/pacman.conf
    chmod: "644"
  scripts:
    src: scripts
    dst: ~/.scripts
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  gitconfig:
    src: extra-configs/gitconfig
    dst: ~/.gitconfig
    chmod: "644"
  zshenv:
    src: extra-configs/zshenv
    dst: ~/.zshenv
    chmod: "755"
  autostart:
    src: extra-configs/autostart
    dst: ~/.autostart
    chmod: "755"
  bin:
    src: bin
    dst: ~/.bin
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  code-flags:
    src: extra-configs/code-flags.conf
    dst: ~/.config/code-flags.conf
    chmod: "644"
  libinput-gestures:
    src: extra-configs/libinput-gestures.conf
    dst: ~/.config/libinput-gestures.conf
    chmod: "644"
  zsh:
    src: zsh
    dst: ~/.config/zsh
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  wlogout:
    src: wlogout
    dst: ~/.config/wlogout
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  wezterm:
    src: wezterm
    dst: ~/.config/wezterm
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  waybar:
    src: waybar
    dst: ~/.config/waybar
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  swaylock:
    src: swaylock
    dst: ~/.config/swaylock
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  starship:
    src: starship
    dst: ~/.config/starship
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  slimbookbattery:
    src: slimbookbattery
    dst: ~/.config/slimbookbattery
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  rofi:
    src: rofi
    dst: ~/.config/rofi
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  redshift:
    src: redshift
    dst: ~/.config/redshift
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  ranger:
    src: ranger
    dst: ~/.config/ranger
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  qt5ct:
    src:  qt5ct
    dst: ~/.config/qt5ct
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  pipewire:
    src: pipewire
    dst: ~/.config/pipewire
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  hypr:
    src: hypr
    dst: ~/.config/hypr
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  gtk-3.0:
    src: gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: "700"
    actions:
      - chmod_dst_folder "700"
  dunst:
    src: dunst
    dst: ~/.config/dunst
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  codef00.com:
    src: codef00.com
    dst: ~/.config/codef00.com
    chmod: "755"
    actions:
      - chmod_dst_folder "755"
  pacman-list:
    src: extra-configs/pacman-list.txt
    dst: ~/pacman-list.txt
    chmod: "644"
    actions:
      - enable_perm_sudo
      - 01_install_packages
      - 02_change_shell
      - 03_add_user_to_groups
      - 04_fix_desktop_portals
      - 05_disable_perm_sudo
profiles:
  station:
    variables:
      is_notebook: false
    include:
      - base
  notebook:
    variables:
      is_notebook: true
    include:
      - base
    dotfiles:
      - slimbookbattery
      - libinput-gestures
  
  system:
    dotfiles:
    - pacman
  base:
    dotfiles:
    - pacman-list
    - scripts
    - gitconfig
    - zshenv
    - autostart
    - bin
    - code-flags
    - zsh
    - wlogout
    - wezterm
    - waybar
    - swaylock
    - starship
    - rofi
    - redshift
    - ranger
    - qt5ct
    - pipewire
    - hypr
    - gtk-3.0
    - dunst
    - codef00.com
    

